name: Docker Image CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file docker/Dockerfile --tag $DOCKER_USER/armadietto:$GITHUB_REF .
    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Push to Docker Hub
      run: docker push $DOCKER_USER/armadietto:$GITHUB_REF
